### ISSUE TITLE
Solve matplotlib dependencies

### ISSUE THREAD

**Issue by mrakitin** [kalebswartz7/SRW-parser#2]
@tacaswell recommended to use PyQt5 < 5.11. @kalebswartz7, please update the requirements to make matplotlib working with PyQt5. I installed it from conda, and it works fine:
```
conda install 'pyqt<5.11' matplotlib
```
Should work fine after the update of the requirements in https://github.com/kalebswartz7/SRW-parser/blob/ed03743c25096182abd5119dde703f68ebbe7e3a/setup.py#L15-L17

**Comment by kalebswartz7** [comment]
Thanks for the feedback. The issue has been fixed here: fe94be6.
